#!/usr/bin/env python
"""Smoke-test a packaged Codex Research Reframer skill pack ZIP."""
from __future__ import print_function

import argparse
import tempfile
import zipfile
from pathlib import Path


REQUIRED_FILES = [
    "skills/system-map/SKILL.md",
    "skills/leverage-scan/SKILL.md",
    "skills/lateral-generate/SKILL.md",
    "skills/lateral-generate/agents/openai.yaml",
    "skills/vertical-audit/SKILL.md",
    "skills/vertical-audit/agents/openai.yaml",
    "skills/idea-card/SKILL.md",
    "skills/reframe-workshop/SKILL.md",
    "examples/physmaster-three-gate/input.md",
    "scripts/validate_outputs.py",
    "scripts/contract.py",
    "skills/reframe-workshop/scripts/validate_outputs.py",
    "skills/reframe-workshop/scripts/contract.py",
    "skills/reframe-workshop/references/stage0_diagnosis.schema.json",
    "CHANGELOG.md",
    "docs/2026-07-01-v0.7-diagnostic-feedback-search-design.md",
    "docs/2026-06-27-v0.5-three-gate-redesign.md",
]

FORBIDDEN_PREFIXES = [
    "reframe-ui/",
    "test-runs/",
]
FORBIDDEN_PART_PREFIXES = (
    "codex-render-smoke-",
    "live-workflow-",
    "2603-25719-paper-",
)


def smoke_test(zip_path):
    zip_path = Path(zip_path)
    if not zip_path.is_file():
        return ["{} does not exist".format(zip_path)]

    errors = []
    with zipfile.ZipFile(zip_path, "r") as zf:
        names = zf.namelist()
        bad_names = [name for name in names if "\\" in name]
        if bad_names:
            errors.append("zip entries must use POSIX '/' paths; found {}".format(bad_names[:5]))
        required_missing = [name for name in REQUIRED_FILES if name not in names]
        if required_missing:
            errors.append("zip is missing required entries: {}".format(required_missing))
        forbidden = [
            name for name in names
            if any(name.startswith(prefix) for prefix in FORBIDDEN_PREFIXES)
        ]
        if forbidden:
            errors.append("zip contains Codex-excluded entries: {}".format(forbidden[:5]))
        forbidden_generated = [
            name for name in names
            if any(part.startswith(FORBIDDEN_PART_PREFIXES) for part in name.split("/"))
        ]
        if forbidden_generated:
            errors.append("zip contains generated test-run entries: {}".format(forbidden_generated[:5]))

        with tempfile.TemporaryDirectory(prefix="research_reframer_codex_zip_") as tmp:
            extract_root = Path(tmp)
            zf.extractall(extract_root)
            for rel in REQUIRED_FILES:
                if not (extract_root / rel).is_file():
                    errors.append("missing after extractall: {}".format(rel))
    return errors


def main(argv=None):
    parser = argparse.ArgumentParser(description="Verify a Codex Research Reframer skill pack ZIP.")
    parser.add_argument("zip_path", help="Path to ZIP generated by scripts/package_zip.py")
    args = parser.parse_args(argv)

    errors = smoke_test(args.zip_path)
    if errors:
        for err in errors:
            print("[ERROR] {}".format(err))
        return 1
    print("[OK] {}".format(args.zip_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
