#!/usr/bin/env python
"""Smoke-test a packaged Research Reframer skill pack ZIP."""
from __future__ import print_function

import argparse
import tempfile
import zipfile
from pathlib import Path


REQUIRED_FILES = [
    "skills/system-map/SKILL.md",
    "skills/leverage-scan/SKILL.md",
    "skills/lateral-generate/SKILL.md",
    "skills/vertical-audit/SKILL.md",
    "skills/idea-card/SKILL.md",
    "skills/reframe-workshop/SKILL.md",
    "examples/physmaster-three-gate/input.md",
    "scripts/validate_outputs.py",
    "scripts/contract.py",
    "CHANGELOG.md",
    "docs/2026-06-27-v0.5-three-gate-redesign.md",
    # reframe-ui channel must ship in the pack (regression guard: a build that
    # drops the UI would otherwise still pass this smoke test) — see CHANGELOG 0.4.1
    "reframe-ui/server.mjs",
    "reframe-ui/ui.html",
    "reframe-ui/package.json",
    "reframe-ui/package-lock.json",
    "reframe-ui/CONTRACT.md",
    "reframe-ui/README.md",
    "reframe-ui/.mcp.json",
    "reframe-ui/.claude-plugin/plugin.json",
]


def smoke_test(zip_path):
    zip_path = Path(zip_path)
    if not zip_path.is_file():
        return ["{} does not exist".format(zip_path)]

    errors = []
    with zipfile.ZipFile(zip_path, "r") as zf:
        names = zf.namelist()
        bad_names = [name for name in names if "\\" in name]
        if bad_names:
            errors.append("zip entries must use POSIX '/' paths; found {}".format(bad_names[:5]))
        required_missing = [name for name in REQUIRED_FILES if name not in names]
        if required_missing:
            errors.append("zip is missing required entries: {}".format(required_missing))

        with tempfile.TemporaryDirectory(prefix="research_reframer_zip_") as tmp:
            extract_root = Path(tmp)
            zf.extractall(extract_root)
            for rel in REQUIRED_FILES:
                if not (extract_root / rel).is_file():
                    errors.append("missing after extractall: {}".format(rel))
    return errors


def main(argv=None):
    parser = argparse.ArgumentParser(description="Verify a Research Reframer skill pack ZIP.")
    parser.add_argument("zip_path", help="Path to ZIP generated by scripts/package_zip.py")
    args = parser.parse_args(argv)

    errors = smoke_test(args.zip_path)
    if errors:
        for err in errors:
            print("[ERROR] {}".format(err))
        return 1
    print("[OK] {}".format(args.zip_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
